# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install dependencies
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables (use ARG to pass build-time variables)
ARG CHAIN_ID
ARG RPC_URL
ARG PRIVATE_KEY
ARG ORACLE_ADDRESS
ARG PINATA_API_KEY

ENV CHAIN_ID=${CHAIN_ID}
ENV RPC_URL=${RPC_URL}
ENV PRIVATE_KEY=${PRIVATE_KEY}
ENV ORACLE_ADDRESS=${ORACLE_ADDRESS}
ENV PINATA_API_KEY=${PINATA_API_KEY}

# Make port 5001 available to the world outside this container
EXPOSE 5001

# Run app.py when the container launches
CMD ["python", "app.py"]
