version: '3.8'

services:
  app:
    build:
      context: .
      args:
        CHAIN_ID: ${CHAIN_ID}
        RPC_URL: ${RPC_URL}
        PRIVATE_KEY: ${PRIVATE_KEY}
        ORACLE_ADDRESS: ${ORACLE_ADDRESS}
        PINATA_API_KEY: ${PINATA_API_KEY}
    ports:
      - "5001:5001"
    environment:
      - CHAIN_ID=${CHAIN_ID}
      - RPC_URL=${RPC_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - ORACLE_ADDRESS=${ORACLE_ADDRESS}
      - PINATA_API_KEY=${PINATA_API_KEY}
    volumes:
      - /tmp:/tmp
